{% set name = "jupyternotify" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 843509e7c3e3369f221a87af310165d51122e0ee8ed1c4ce0cdc34338e17b73a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - ipython
    - jupyter

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupyternotify

about:
  home: http://github.com/ShopRunner/jupyter-notify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Jupyter Notebook magic for browser notifications of cell completion'
  description: |
    This package provides a Jupyter notebook cell magic %%notify that notifies
    the user upon completion of a potentially long-running cell via a browser
    push notification. Use cases include long-running machine learning models,
    grid searches, or Spark computations. This magic allows you to navigate
    away to other work (or even another Mac desktop entirely) and still get a
    notification when your cell completes. Clicking on the body of the
    notification will bring you directly to the browser window and tab with
    the notebook, even if you're on a different desktop (clicking the "Close"
    button in the notification will keep you where you are).
  doc_url: https://github.com/ShopRunner/jupyter-notify
  dev_url: https://github.com/ShopRunner/jupyter-notify

extra:
  recipe-maintainers:
    - djsutherland
