travis:
  secure:
    BINSTAR_TOKEN: lSTvfnglC0Pt207zUnEBjiNQkhvQDiCHtZMi6E0WfDZ6C3CNcv1nYnSr609CrVodaNdwlC2wa0k7m118hbMslS/k84icbWj7jfQqkMyGPNCksxR7Ujp5UjpmYyFwRjIl9VCdbmYoXpzq1ljRNcRv5Mn8F/t0a1yu2UIRVtTvBPrDJpc5uZ5gGprNprJRTfRMaj1GeBwZ4uJ1VLWMvqzjkWI6t0t3OibGk3RSiUUFOl4rYSCuJLRmp8+zC6dqionYR7JpXrqzwPDJCQOVJ+C1SLKghT/vV6Z1ph0bdauNSlhERSXaTZ238bLoa17ucUyCIYbs5UUIrnFy/qdCzixNSwqsZKiJFP3f+n1dudoHk6n6TDvC19FgYBD4xsSbHlKQ49gBUEV0CNHhSLx26tNkDKwOZimNN82Y7QRqeBym5g5fMblG8b39bJhShj4++8ZEojphIP9x9PuIDAIMMi7pNzmAAd4dmtmbSpL6rUSj36zo49vwIquDxEM+F+ZoJURHeHQ6zjhtpYC+NXsd+vLLPthdIqoy1C5uhvQIGlXusKNIohilcBmTEZThFLB5VVNHTOkQb1n9MdRYaK+uXt5WvxKq8aShRUqAf72/k5BqoLIx6deRcxUZ22jQI9vm1IaCcv4pVk5+UhVmMUm/keDftpbh/QPR8i2e8gvf7qFz0L4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
