travis:
  secure:
    BINSTAR_TOKEN: cGU5u2xzz7JxUki0Tsmi/PEEV9CtZAChYeDB00a4pC8aEpWnUqfScoTNJWM/vts/fqpj/SkI/rTqc/MOVCdF5Agh/g1OCpCZK2yzEasQgyf5Lnb+V9y1AfXnnzjaEFtInNN+iYmcZaxaIICeG7VkrJfRBX4W09b8PUwtPc1MqBKd1RUqK6RW6M+/Bxa1plK2AAm+M9Jk4EuaariWpwz4H9OCqjSK6o/HTLMmY59AGzdm2TXThVxpf4FiTFoU23rE1k7k+14SgVjOnY4+KdrqIqZRJxt/EFHbMzi1E5iXeoQ0p4l0Ua4ztFatxZQWOyxcIXGgzIeagqi3q1Ar3OMvQjhJb8McNCClUTMQw1rxtWsgC+6kWc4XBbjLJMAT/uG67O6kP4yFkOD4icMcX7hvofd2Tn84pFhK83Wp9jX6k5oD126LYxIN6Bv0ZN8byD3qx1EPyfb9nkr5lkfK5vVjxHTLlqSqHkl5lZMxW2PJbaaKEIvGMjNx1A4R7R0wiRixljrdItnaOPS9AwLZfe5E8R/mQhiF2KzEorynUzfpb+7D87Su4Zz1KhWtDs7p2/JK8cDA6CkJerwAbqjzoiybIlC34CBHAU9AxVmTgGITQROgKejyfbwjg/rUkVp2uzzS7SOvUh7qIHxPDaK37hX13GElhMN21jBY61igPghLy4Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
